version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8098:80
    links:
      - fpm
    volumes: 
      - ./:/var/www/HiSmithJob
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes: 
      - ./:/var/www/HiSmithJob
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel