version: '3.4'
networks:
  laravel:
services:
  site:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/HiSmithJob
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: homestead
      PMA_PASSWORD: secret
    volumes:
      - ./upload.ini:/usr/local/etc/php/php.ini
    ports:
      - "8888:80"
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/HiSmithJob
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/HiSmithJob
    working_dir: /var/www/HiSmithJob
    depends_on:
      - php
    networks:
      - laravel
  npm:
    image: node:14.8
    volumes:
      - ./:/var/www/HiSmithJob
    working_dir: /var/www/HiSmithJob
    entrypoint: ['npm']
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/HiSmithJob
    depends_on:
      - mysql
    working_dir: /var/www/HiSmithJob
    entrypoint: ['php', '/var/www/HiSmithJob/artisan']
    networks:
      - laravel